services:
- docker
addons:
  apt:
    packages:
      - docker-ce
before_install:
- docker build -t somleng/docker-freeswitch 1.8
script:
- docker run --rm somleng/docker-freeswitch /usr/bin/freeswitch -version
